### ISSUE TITLE
How to specify an scss template

### ISSUE THREAD

**Issue by RobertCordes** [jkphl/gulp-svg-sprite#10]
Hey,

how can I specify the scss template to be used? And can I also configure the destination for the generated scss file or should I just move afterwards?

Thanks in advance,
Robert

**Comment by jkphl** [comment]
You can control all aspects of the creation process in advance:

```javascript
var config = {
	mode: {
		css: {
			render: {
				scss: {
					template: 'path/to/scss/template/relative/to/dest/dir',
					dest: 'dest/to/created/scss/file/relative/to/dest/dir'
				}
			}
		}
	}
}
```

Please see [the documentation](https://github.com/jkphl/svg-sprite/#e-rendering-configurations) for further details on rendering configurations.

**Comment by RobertCordes** [comment]
Thanks @jkphl, that helped.

**Comment by jkphl** [comment]
You're welcome! :+1:

**Comment by thalesfsp** [comment]
Hello @jkphl Do you have any update about the native PNG fallback support? Cheers!

**Comment by jkphl** [comment]
@thalesfsp I'm very sorry but no, not yet. There are new versions of [node-iconizr](https://github.com/jkphl/node-iconizr/tree/dev) and [grunt-iconizr](https://github.com/jkphl/grunt-iconizr/tree/dev) in the `dev` trees, but unfortunately I'm so utterly lacking time that I don't manage to write a proper documentation and release them finally. The Gulp plugin shouldn't be that much work then, though. I'll try to do my best ...
