### ISSUE TITLE
Empty SVG

### ISSUE THREAD

**Issue by tiagoporto** [jkphl/gulp-svg-sprite#14]
Hello @jkphl

In my gulpfile.js, I use gulp-svg-sprite, but when the project is not necessary to work with any svg sprite is always generated an svg file empty.

How do I fix this?

**Comment by jkphl** [comment]
Sorry @tiagoporto, but this is beyond *gulp-svg-sprite*'s horizon, and as I'm not a regular Gulp user, I'm not able to help you with this.
