### ISSUE TITLE
"{}" is not a valid mode configuration

### ISSUE THREAD

**Issue by nilssolanki** [jkphl/gulp-svg-sprite#15]
I tried to replace the old gulp-svg-sprites with you gulp-svg-sprite package, and I'm running into the following error:

	events.js:72
	        throw er; // Unhandled 'error' event
	              ^
	ArgumentError: SVGSpriter.compile: "{}" is not a valid mode configuration

And my gulp task:

    gulp.task('icons', [], function(){
        var env = util.env();

        return gulp.src(config.icons.src.files)
            .pipe($.plumber({ errorHandler: util.error }))
            // Create SVG Sprite
            .pipe( $.svgSprite({ mode: { symbols: true } }) )
            .pipe( $.gulpif( env.name === env.types.DIST,
                $.gzip({ append: false }),
                $.gutil.noop())
            )
            .pipe( gulp.dest(config.icons[env.name].path) );
    });

The configuration is clearly there. Any idea what could be causing this?

**Comment by jkphl** [comment]
Hi @nilssolanki,

please be aware, that *gulp-svg-sprite* **is not a drop-in replacement** for *gulp-svg-sprites* (although many features are similar). Please stick to the docs and see how to build a valid configuration for the spriter.

Cheers,
Joschi

**Comment by nilssolanki** [comment]
Yes, but I only used the basic mode configuration of svg-sprite:
`{ mode: { symbols: true } }`. Yet somehow he doesn't seem to find any config at all:

ArgumentError: SVGSpriter.compile: "{}" is not a valid mode configuration

**Comment by jkphl** [comment]
As I said, please stick to the docs. `symbol**s**` is not a valid mode, it has to be `symbol`.

**Comment by nilssolanki** [comment]
Whoops, thanks. I didn't realize the extra *s*.

**Comment by jkphl** [comment]
You're welcome. If all problems were that easy, right?! ;)
