### ISSUE TITLE
Preview Page

### ISSUE THREAD

**Issue by zslabs** [jkphl/gulp-svg-sprite#18]
Thanks for creating this! Any chance of a preview page similar to how it was done in gulp-svg-sprites? We're building documentation pages and it'd be nice if we could reference the included/updated SVGs automatically. We've done something similar with IcoMoon's downloaded preview they give you, but really liked the way gulp-svg-sprites automatically created this for us. Thanks again!

**Comment by jkphl** [comment]
Hi @zslabs,

I never worked with *gulp-svg-sprites* (and totally lack the time of doing so, sorry), so could you please provide an example of how @shakyShane's one looked like?

Thanks a lot, cheers,
Joschi

**Comment by zslabs** [comment]
Did you want a visual representation? Here's the usage part on his README https://github.com/shakyShane/gulp-svg-sprites#usage

it's basically a standard HTML file that has the SVGs automatically in a grid and labeled. I'm happy to do the DOM behind this, just lack the Node knowledge to make it happen.

**Comment by jkphl** [comment]
Just to make sure: You did realize the `mode.<mode>.example` option, right (see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties))? Doesn't this suit your needs?

**Comment by zslabs** [comment]
That's it! Sorry about that, blame @mcraiganthony for making me jump the gun.

**Comment by jkphl** [comment]
;) No problem. I was just wondering ... Let me know if you need any assistance!
