### ISSUE TITLE
Don't include XML prologue, DOCTYPE, etc. in generated SVG sprite file when using inline symbol mode

### ISSUE THREAD

**Issue by troywarr** [jkphl/gulp-svg-sprite#2]
In my project, I'm using the following gulp task:

    gulp.task('svg-icons', function() {
      return gulp
        .src("./src/icons/**/*.svg")
        .pipe(plumber(handleError))
        .pipe(svgSprite({
          mode: {
            symbol: {
              inline: true,
              example: true
            }
          }
        }))
        .pipe(gulp.dest('./dist'));
    });

Running it creates the following file structure:

    dist/
      symbol/
        svg/
          sprite.symbol.svg
        sprite.symbol.html

My expectation is that since I've set `mode.symbol.inline` in my config object to `true`, the file `sprite.symbol.svg` would only consist of the `<svg>` element and any nested elements/content (i.e., not the XML namespace declaration, DOCTYPE, etc.). In another step of my build process, I'm including the full output of `sprite.symbol.svg` in my main HTML file, so only the `<svg>` element and its contents are needed there (otherwise I'll need to strip them somehow).

Does this seem like a bug, or am I not understanding (or using) the `inline` option correctly?

Great work here, BTW!

**Comment by jkphl** [comment]
Hi @troywarr,

to answer your last question first: I'd consider it a bug — with an easy short-term solution:

To quickly get rid of the the XML and doctype declaration, simply use the [two coresponding config options](https://github.com/jkphl/svg-sprite#c-common-svg-options).

And of course you are right, when using the `inline` option, these parts shouldn't be generated by default. I will have a look at it!

Cheers,
Joschi

**Comment by jkphl** [comment]
As of release f57a1d247cdced12d8f016b12e6f205711fe5f58, *gulp-svg-sprites* shouldn't create XML and doctype declarations for inline sprites anymore. Would you please check if this works for you now? I'll close the issue, but please feel free to re-open in case of further problems.

Cheers,
Joschi

**Comment by troywarr** [comment]
Looks great! After updating, only `<svg>` and its contents appear in the generated `sprite.symbol.svg` file.

Thanks so much for your help!
