### ISSUE TITLE
Invalid mode configuration

### ISSUE THREAD

**Issue by sanjaydev** [jkphl/gulp-svg-sprite#22]
My Code in Gruntfile.js

```js
svg_sprite      : {
            your_target: {
                cwd: 'images/svg/fixture',
                src: ['*.svg'],
                dest: 'images/svg/expected',
                options     : {
                   shape               : {
                    dimension       : {         // Set maximum dimensions 
                        maxWidth    : 32,
                        maxHeight   : 32
                    },
                    spacing         : {         // Add padding 
                        padding     : 10
                    },
                    dest            : 'out/intermediate-svg'    // Keep the intermediate files 
                },
                }
            }
        },

grunt.registerTask("start", ["svg_sprite"]);
grunt.loadNpmTasks('grunt-svg-sprite');
```

using run command: grunt svg_sprite

```bash
Getting error:
Warning: SVG sprite compilation failed with message: ArgumentError: SVGSpriter.compile: "{}" is not a valid mode configu ration Use --force to continue.
```

PLEASE HELP ME TO FIX THIS ISSUE.

**Comment by jkphl** [comment]
Hi @sanjaydev,

your configuration needs to enable at least one sprite mode. Please [see here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#output-modes) for further information about the output modes and / or use the [configuration kickstarter](http://jkphl.github.io/svg-sprite/) for creating a config object.

Also, please give your issue a proper title and formating next time, that makes it easier to digest! ;)

Cheers and good luck,
Joschi

**Comment by cshold** [comment]
What about the [modeless option](https://github.com/jkphl/svg-sprite#d-no-sprite-at-all)? I can't find a way to only optimize svgs without creating the sprite without getting this error.

**Comment by jkphl** [comment]
@cshold To be honest: I didn't try that in ages, might be broken?! If so, would you mind opening another issue? I'd go for SVGO alone if I only wanted to optimize the SVG.

In any case, as @sanjaydev added `spacing` and `dimension` options, I didn't expect him to optimize the SVGs only.

**Comment by cshold** [comment]
I tried going with SVGO alone, but it won't convert to `symbol` elements which is a big bummer. At some point in the svg sprite creation, I want to hijack it so the output goes to separate files instead of into a sprite. Any pointers, or is that well beyond the scope of this?

**Comment by jkphl** [comment]
Ah, right. SVGO of course does optimization only. On the other hand, with a modeless configuration (even if it worked) you wouldn't get symbols either, as this is exclusive to the symbol mode. I'll try to fix the modeless run however as soon as I can.
