### ISSUE TITLE
Dependency Suggestion

### ISSUE THREAD

**Issue by zslabs** [jkphl/gulp-svg-sprite#28]
Hey Joschi,
Just noticed a npm suggestion they had when doing an update with your module:

```The peer dependency vinyl@^0.4.6 included from gulp-svg-sprite will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.```

Just a heads up for the future. Thanks again for making this package!

**Comment by jkphl** [comment]
Hey @zslabs, please update to the latest version. [This issue](https://github.com/jkphl/gulp-svg-sprite/issues/25) has already been resolved. Cheers

**Comment by zslabs** [comment]
Awesome, thanks man!
