### ISSUE TITLE
Problem with svgId

### ISSUE THREAD

**Issue by FauzanKhan** [jkphl/gulp-svg-sprite#29]
The svgId property is not working as expected. I'm trying to add 'icon-' prefix to the id of every symbol in the sprite created by the gulpfile below but the symbols only have their file name as their IDs-

<pre><code>
var gulp = require('gulp');
var svgSprite = require('gulp-svg-sprite');
var pages = ['home', 'offers', 'plays'];
gulp.task('sprite', function() {
  pages.forEach(function(page){
    gulp.src('svgs/'+page+'/*.svg')
    .pipe(svgSprite( 
      config = {
      mode : {
        symbol : {
          dest : '.',
          sprite : page+'/concatanated.svg',
        }
      },
      svgId : 'icon-%f'
    }
  ))
  .pipe(gulp.dest('svgs/build/'));
  })
});
gulp.task('default', ['sprite']);
</code></pre>

**Comment by jkphl** [comment]
Hi @FauzanKhan,

it seems to me that you are mixing *gulp-svg-sprite* and *gulp-svg-sprite*__*s*__ by @shakyshane (which isn't maintained anymore), is that possible? Please see the [relevant documentation section](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids) for details on how to control the shape ID in *gulp-svg-sprite*.

Cheers,
Joschi

**Comment by FauzanKhan** [comment]
Hi @jkphl 

I'm using gulp-svg-sprite. I was referring to gulp-svg-sprites' documentation to achive what I want, I found that gulp-svg-sprite's mode.<mode>.prefix would allow me to get the desired result. So, I placed <code>prefix : 'icon-'</code> inside my symbol object but still I'm unable to add 'icon-' prefix to the the IDs of the symbol tags in the generated sprite.

Regards
Fauzan

**Comment by jkphl** [comment]
You are still not using the correct configuration options. As I said, please refer to the [relevant documentation section](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-ids). Your config needs to look something like this (untested):

```javascript
var config = {
	shape {
		id {
			generator: 'icon-%s'
		}
	}
}
```

**Comment by FauzanKhan** [comment]
You were right. This solved the issue for me. Thank you.
