### ISSUE TITLE
Remove 'mode' name from output directory

### ISSUE THREAD

**Issue by brianO3world** [jkphl/gulp-svg-sprite#30]
Hey!

Trying to get set-up with this new package since 'gulp-svg-sprites' is no longer working. I have my SCSS and Sprite exporting but it's writing my directory structure inside of a 'view' folder on my site root. Is there a way to remove the 'mode' name folder and have the output SCSS and SVG files places in the directories I want?

For example:

What I am getting:

view > images > 'test.svg'
view > styles > scss > _partial > '_sprite.scss'

What I want:

images > 'test.svg'
styles > scss > _partial > '_sprite.scss'

I need these generated assets to go into the folders I have existing on my site otherwise I'm moving stuff around every time. How might I do this?

Thanks,
Brian

**Comment by jkphl** [comment]
Hi @brianO3world,

it's most likely the `mode.<mode>.dest` property you will want to use, please see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties):

```javascript
var config = {
	mode : {
		view : {
			dest: '.'
		}
	}
}
```

There's also a special section about [output destinations](https://github.com/jkphl/svg-sprite#output-destinations) in the docs which might help you‽

Cheers,
Joschi

**Comment by brianO3world** [comment]
I was able to finally test this and everything worked great! Along with a few other updates this is working as a nice replacement for `gulp-svg-sprites`. Thanks!

**Comment by jkphl** [comment]
You're welcome! :)
