### ISSUE TITLE
receiving class name without "."

### ISSUE THREAD

**Issue by nongrata88** [jkphl/gulp-svg-sprite#34]
I changed stylus template in order to receive another output:
```
{{#shapes}}
{{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}
  background-position {{position.relative.xy}}
  width {{width.outer}}px
  height {{height.outer}}px

{{/shapes}}
```

This outputs to stylus:
```
.svg-icon-1
  background-position 95.23809523809524% 45%
  width 10px
  height 10px

.svg-icon-2
  background-position 0 100%
  width 10px
  height 10px
```

My goal is to have such stylus output, where background-position, width and height are not set to css classes directly, but are kept in a separate variable, named the same as the file:
```
$svg-icon-1 = 95.23809523809524% 45% 10px 10px;
.svg-icon-1
  background-position $svg-icon-1[0]
  width $svg-icon-1[1]
  height $svg-icon-1[2]

$svg-icon-2 = 0 100% 10px 10px;
.svg-icon-2
  background-position $svg-icon-2[0]
  width $svg-icon-2[1]
  height $svg-icon-2[2]
```

In order to get that stylus output I changed the template file:

```
{{#shapes}}
${{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}} = {{position.relative.xy}} {{width.outer}}px {{height.outer}}px;
{{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}
  background-position {{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}[0]
  width {{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}[1]
  height {{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}[2]

{{/shapes}}
```

where the code below should produce the variable containing $ and the name of .svg file, containing background-position at [0], width at [1] and height at [2]
```
${{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}} = {{position.relative.xy}} {{width.outer}}px {{height.outer}}px;
```

The issue is that this part of code:
```
{{#selector.shape}}{{#escape}}{{expression}}{{/escape}}{{^last}},{{/last}}{{/selector.shape}}
```

produces the css class, containing the "." + "filename", with my template resulting in:
```
$.svg-icon-2
```

that is compiled by stylus not as a variable, but as a property (everything started with a dot is assumed to be a property). 

How can I get the pure filename without a dot at the beggining, not a css class? Is it possible? In gulp.spritesmith it is possible by simply using {{strings.name}} in template, what gives a user much more control and possibilities to get the needed output.

I assume that the name of the file is this - {{expression}} , but it doesn't output anything if is used out of {{#selector.shape}}{{/selector.shape}}

**Comment by jkphl** [comment]
Hey @nongrata88,

first of all, the **file name**, i.e. the name of the sprite SVG file that will be created, is not available as a variable value during the templating process, as under normal circumstances this is of no relevance for the sprite. Please refer to the [templating guide](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) for an overview of the complete templating data and the meaning of the `expression` variable.

Second, if the value you need just is something like *"the regular selector without the dot in the beginning"*, you may pass in a custom function into the templating process, similar to the pre-defined [classname()](https://github.com/jkphl/svg-sprite/blob/83626a62880207ccb5fb52767972dac89e21e47b/lib/svg-sprite/layouter.js#L69) function, call this function with the selector as argument and let it return the value you need. You might want to read the section about lambda function in the [Mustache docs](http://mustache.github.io/mustache.5.html) to fully understand how to write custom functions for Mustache. You may also have a look at [another example](https://github.com/jkphl/svg-sprite/issues/32#issuecomment-65403660) creating PNG file names. I hope this helps!

Finally, there's no sense in referring to other packages like *gulp-spritesmith* as they are not related to *(gulp-/grunt-)svg-sprite* in any way. To be honest, I don't even know how *gulp-spritesmith* does its job (I'm sure it's a fine piece of software though).

On another note, I'm not a Stylus user at all, so I don't know about the structure of Stylus stylesheets and can't help you with your particular template. Sorry for that.

Cheers & good luck,
Joschi
