### ISSUE TITLE
gulp-svg-sprite adds random characters to classes

### ISSUE THREAD

**Issue by atomless** [jkphl/gulp-svg-sprite#36]
Gulp-svg-sprite is adding random characters to the beginning of symbol group classes. It's not consistent either. The same "color1" class is used on a number of svg symbols, after svg-sprite has concatenated them the classes all have an extra two characters added to the start of the classname like so : "aacolor1", "adcolor1", "ahcolor1" etc. Seems very odd behaviour to me!

**Comment by jkphl** [comment]
Please see [here](https://github.com/jkphl/svg-sprite/issues/110);
