### ISSUE TITLE
Dead link on svg4everybody polyfill in examples

### ISSUE THREAD

**Issue by jekaj** [jkphl/gulp-svg-sprite#39]
Hi, thank you for great tool. I found a dead link on polyfill svg4everybody in templates for symbol and defs examples. [**This**](https://rawgit.com/jonathantneal/svg4everybody/master/svg4everybody.js) link is not working now. You can use this [**CDN**](https://cdnjs.cloudflare.com/ajax/libs/svg4everybody/2.0.0/svg4everybody.min.js) or another.

Ps. Also, you forget call the script.
```javascript
<script>svg4everybody();</script>
```

**Comment by jkphl** [comment]
Thanks for pointing this out. Should be fixed with the next release of [svg-sprite](https://github.com/jkphl/svg-sprite). :+1:
