### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by tiagoporto** [jkphl/gulp-svg-sprite#4]
I cant install the package

```
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/lodash/lodash)
```
And the installation doesnt end

Win 7 - 64bits

**Comment by jkphl** [comment]
Hi @tiagoporto,

I just tried the very same and it worked without problems. Did you remember to install all prerequisites (e.g. Git) and restart your shell before trying the installation?

Cheers, Joschi

**Comment by tiagoporto** [comment]
Hello @jkphl,

I have GIT. There is another prerequisite?

**Comment by jkphl** [comment]
Nothing that wouldn't come automatically when installing via `npm`, as far as I know.

As I said, it just works perfectly fine for me on both Win 7 and Win 8.1. Unfortunately I don't have any clue what could be your problem. Did you try installing *gulp-svg-sprite* globally or locally?

**Comment by tiagoporto** [comment]
Yeah!!

In Win8 Works.

Thanks
