### ISSUE TITLE
Allow placing the example demo html file outside destination folder

### ISSUE THREAD

**Issue by binarykitchen** [jkphl/gulp-svg-sprite#40]
The HTML example document demoing the svg sprites can have any path, see option `mode.<mode>.example.dest` in https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#common-mode-properties

Would be great to be able to define it outside of the given destination folder.

**Comment by jkphl** [comment]
@binarykitchen You should totally be able to do so by using the proper path for the example's `dest` option, but please be aware that the CSS files might not be generated twice (the example should try to use the "real" ones that your configuration is producing anyway). Please let me know if this doesn't work for you.

**Comment by binarykitchen** [comment]
yeah, it worked, thx

**Comment by KasperChristensen** [comment]
@binarykitchen did you get it to work with an absolute path?
I can't move it out of the folder, like documentation also says:
https://github.com/jkphl/svg-sprite/blob/master/bin/config.yaml

example:
    ...
    dest:
      description      : HTML document destination (relative to the --css-dest)
      default             : sprite.css.html
      map                 : mode.css.example.dest

**Comment by KasperChristensen** [comment]
Oh my problem was in gulp.dest()
