### ISSUE TITLE
Invalid counter created files

### ISSUE THREAD

**Issue by mrmlnc** [jkphl/gulp-svg-sprite#41]
If run the task without the svg files in a directory, the plugin will show an incorrect amount created files (but the files are not created).

SVG: 0
Created files: 1 SVG + 1 Less

![image](https://cloud.githubusercontent.com/assets/7034281/12117877/6ca93e5a-b3d4-11e5-9b7a-802a8f6348cc.png)

**Comment by mrmlnc** [comment]
Ooops, it seems this issue had to create in the `svg-sprite` repository.

**Comment by jkphl** [comment]
Thanks for moving.
