### ISSUE TITLE
modeless: {} not a valid mode config

### ISSUE THREAD

**Issue by cshold** [jkphl/gulp-svg-sprite#42]
Get the following error when trying to use the modeless approach:
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
ArgumentError: SVGSpriter.compile: "{}" is not a valid mode configuration
```

Theoretically should work as listed in https://github.com/jkphl/svg-sprite#d-no-sprite-at-all

**Comment by jkphl** [comment]
Thanks for pointing this out, @cshold, and sorry for not responding earlier. This doesn't seem to be a problem specific to the Gulp wrapper, so I filed a [new issue over at svg-sprite](https://github.com/jkphl/svg-sprite/issues/158).
