### ISSUE TITLE
gulp svg sprite not generating

### ISSUE THREAD

**Issue by qasimalyas** [jkphl/gulp-svg-sprite#44]
Hello,

I just setup a local project and was trying to get the `gulp-svg-sprite` plugin to work but i'm having some problems.

I have a gulpfile with a [basic example](https://github.com/jkphl/gulp-svg-sprite#examples) taken from the homepage and it just doesn't do anything. The task itself starts and finishes but nothing gets generated. 

If i use the original [svg-sprite](https://github.com/jkphl/svg-sprite) plugin and run the cli ```svg-sprite --css --css-render-css --dest=out *.svg``` it works fine and does what i expect but my gulp example - which is taken from the main page does nothing.

I've put [my example on github](https://github.com/qasimalyas/svgsprites), can someone care to look at this and explain what could be the problem?

**Comment by qasimalyas** [comment]
Its working now. Not sure what it was because i didn't change a thing. Closing issue.

**Comment by jkphl** [comment]
Im happy you could solve it yourself, @qasimalyas!
