### ISSUE TITLE
Plugin don't work on Gulp 4

### ISSUE THREAD

**Issue by corsairdnb** [jkphl/gulp-svg-sprite#45]
Does `gulp-svg-sprite` work with new Gulp version?
Now running plugin with any options gives such error:
```
[12:40:50] Error in plugin 'gulp-svg-sprite'
Message:
    Skipping "%s" (%s)
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```
I suppose this is due to deprecated status of `gulp-util` package.

**Comment by jkphl** [comment]
@corsairdnb Thanks for the heads up. I'd love to get help with this as I'm neither a regular Gulp user, nor did I ever try Gulp 4 so far. Anyone?

**Comment by corsairdnb** [comment]
@jkphl I'll try to find out whats the problem. Anyway thanks for great plugin **svg-sprite**!

**Comment by jkphl** [comment]
@corsairdnb Awesome, thanks! You're welcome!

**Comment by KevinSleegers** [comment]
Hi, I'm having the same issue. Have you found a solution yet?

**Comment by corsairdnb** [comment]
I've recently solved the problem by clean installing all the gulp plugins/dependencies and rewriting gulp-svg-sprite config. Now it works. So maybe problem was actually not in the plugin, but in the way I used it.

**Comment by Saturate** [comment]
I'm having this issue. And can't find out whats wrong.

**Comment by Nejik** [comment]
this problem appears with empty svg file

**Comment by chrisgerne** [comment]
Below is where my code was erroring

```
gulp.task('providers_strip_svg_props', function (done) {
    gulp.src(providers_spriteSrc)
        .pipe(plumber({
            handleError: function (err) {
                console.log(err);
                this.emit('end');
            }
        }))
        .pipe(rsp.remove({
            properties: [rsp.PROPS_STROKE, rsp.PROPS_FILL, rsp.PROPS_FONT, 'color', 'clip-rule',],
            stylesheets: true,
            inline: true,
            log: true
        }))
        .pipe(gulp.dest(providers_spriteStripped));
    done();
});
```


**
I ended up getting it to work by removing the plumber shenanigans. Below is my working code.
**
```
gulp.task('providers_strip_svg_props', function (done) {
    gulp.src(providers_spriteSrc)
        .pipe(rsp.remove({
            properties: [rsp.PROPS_STROKE, rsp.PROPS_FILL, rsp.PROPS_FONT, 'color', 'clip-rule',],
            stylesheets: true,
            inline: true,
            log: true
        }))
        .pipe(gulp.dest(providers_spriteStripped));
    done();
});
```

**Comment by SultanMashukov** [comment]
Check encodings of your svg files. I had UTF-16 encoding in one file. After saving it to UTF-8, it worked!
