### ISSUE TITLE
Svg circle renders as square in Firefox (and occasionally in IE, Safari and Chrome too)

### ISSUE THREAD

**Issue by mpiasta-ca** [jkphl/gulp-svg-sprite#47]
I've got a series of svg flag icons that have a `<circle>` applied to them, and exported with Illustrator. For a strange reason, the svg will randomly render as a square.

![square-country-icon-bug](https://cloud.githubusercontent.com/assets/672103/13414156/5158b304-df05-11e5-93a1-781aca7103e5.png)

It's as-if Firefox has a mind of its own and renders the icon whichever way it chooses.

On another page, I use the same icons, and this is how they render in Firefox:

![region-ff-bug](https://cloud.githubusercontent.com/assets/672103/13470434/010f047c-e061-11e5-90a3-c12249e5459b.png)

The same page in Internet Explorer (Edge), which somehow renders the outline of the icon, but doesn't render its internals:

![region-ie-bug](https://cloud.githubusercontent.com/assets/672103/13470442/0d4e4c16-e061-11e5-9e2d-c55a7aec8883.png)

On very rare occasions, I see similar behavior with Chrome, but for the most part, Chrome is rendering correctly.

HOWEVER, when I render each svg directly with an `<img>` tag (non-sprite), there are no issues in any browser. So not sure what it is about svg-sprite that is causing the problems.

Example svg:

```
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve">
<g>
    <defs>
        <circle id="SVGID_109_" cx="25" cy="25" r="25"/>
    </defs>
    <clipPath id="SVGID_110_">
        <use xlink:href="#SVGID_109_"  style="overflow:visible;"/>
    </clipPath>
    <g style="clip-path:url(#SVGID_110_);">
        <rect x="-1" style="fill:#FFFFFF;" width="52" height="50"/>
        <rect x="-1" style="fill:#BF0A30;" width="8.9" height="50"/>
        <path style="fill:#BF0A30;" d="M13.1,26.2l-1.4,0.5l6.4,5.6c0.5,1.4-0.2,1.9-0.6,2.6l6.9-0.9l-0.2,7h1.4l-0.1-7l6.9,0.8
            C32,33.9,31.6,33.4,32,32l6.4-5.3l-1.1-0.4c-0.9-0.7,0.4-3.4,0.6-5.1c0,0-3.7,1.3-4,0.6l-1-1.8l-3.4,3.7c-0.4,0.1-0.5-0.1-0.6-0.4
            l1.6-7.8L28,16.9c-0.2,0.1-0.4,0-0.6-0.2L25,11.9l-2.5,5c-0.2,0.2-0.4,0.2-0.5,0.1l-2.4-1.3l1.4,7.7c-0.1,0.3-0.4,0.4-0.7,0.2
            l-3.2-3.7c-0.4,0.7-0.7,1.8-1.3,2c-0.6,0.2-2.4-0.5-3.7-0.7C12.7,22.7,14,25.3,13.1,26.2L13.1,26.2z"/>
        <rect x="42.1" style="fill:#BF0A30;" width="8.7" height="50"/>
    </g>
</g>
<g>
    <path style="fill:#686868;" d="M25,50.025c-3.378,0-6.656-0.662-9.741-1.967c-2.98-1.261-5.656-3.065-7.955-5.363
        c-2.298-2.299-4.103-4.975-5.363-7.955C0.637,31.655-0.025,28.378-0.025,25c0-3.378,0.662-6.656,1.966-9.741
        c1.261-2.98,3.065-5.656,5.363-7.955s4.975-4.103,7.955-5.363C18.344,0.637,21.622-0.025,25-0.025c3.378,0,6.655,0.662,9.74,1.966
        c2.98,1.261,5.656,3.065,7.955,5.363c2.298,2.298,4.103,4.975,5.363,7.955c1.305,3.085,1.967,6.362,1.967,9.741
        c0,3.378-0.662,6.655-1.967,9.74c-1.261,2.98-3.065,5.656-5.363,7.955c-2.299,2.298-4.975,4.103-7.955,5.363
        C31.655,49.363,28.378,50.025,25,50.025z M25,0.025c-3.372,0-6.643,0.661-9.721,1.963C12.305,3.246,9.634,5.046,7.34,7.34
        c-2.293,2.294-4.094,4.965-5.352,7.939C0.686,18.357,0.025,21.628,0.025,25c0,3.371,0.661,6.643,1.963,9.721
        c1.258,2.975,3.059,5.646,5.352,7.939c2.294,2.293,4.965,4.094,7.939,5.353c3.079,1.302,6.35,1.962,9.721,1.962
        c3.371,0,6.643-0.66,9.721-1.962c2.975-1.259,5.646-3.06,7.939-5.353c2.293-2.294,4.094-4.965,5.353-7.939
        c1.302-3.078,1.962-6.35,1.962-9.721c0-3.372-0.66-6.643-1.962-9.721c-1.259-2.974-3.06-5.645-5.353-7.939
        c-2.294-2.293-4.965-4.094-7.939-5.352C31.643,0.686,28.371,0.025,25,0.025z"/>
</g>
</svg>
```

**Comment by jkphl** [comment]
@mpiasta-ca Thanks for reporting, although this really sounds odd.

*svg-sprite* basically doesn't touch the original SVG sources except:

* IDs are namespaced so that there's no ID conflict when merging several SVG sources into the sprite,
* You might choose to use an SVG optimizer — SVGO in this case — who will simplify the SVG source. SVGO is known for using some rather aggressive plugins that might render certain SVG sources useless.

I'd recommend the following steps to narrow down the problem:

* Disable the SVGO transformation to see if it works without.
* Disable single SVGO plugins to see if it works without (you might want to use the [online configurator](http://jkphl.github.io/svg-sprite) for that).
* Compare your original source with the resulting part of the final sprite and see what differences are there.

I think it's unlikely that *svg-sprite* is really corrupting your SVG sources as then it wouldn't be a random thing.

**Comment by mpiasta-ca** [comment]
I turned off SVGO but did not make a difference.

But today I noticed something new. Because the "selected" icon appears elsewhere on our website (in the website footer, the same icon is used to indicate the user's current selected location), means the "selected" icon is being called twice, and the second iteration is the one that renders incorrectly. If I remove that footer icon so there is no duplicate icons, the icons in the country list render without any issues.

So there is something about having the icon render twice that causes an issue, maybe a conflict based on the id of the icon name.

What makes this problem harder to isolate is that we're using angular-material with `<md-icon md-svg-icon="..."></md-icon>` to render the icons. So now I'm not sure if the issue is with the svg-sprite, or with angular-material.

I tried using a plain `<img src="sprite.svg#region-us">` element to render the icons in the svg-sprite, but we are exporting the svg-sprite in defs mode (otherwise it won't work with angular-material's md-icon element). So when using `<img>` element, or even accessing the sprite/id directly in browser, nothing renders.

**Comment by mpiasta-ca** [comment]
I reproduced the bug in plnkr. Seems to happen specifically when the md-icon (from the svg sprite icon set) is used more than once on the page, and when that instance is hidden using ng-show (in our application, the icon is rendered in md-sidenav, so it switches state between open/hidden).

https://plnkr.co/edit/UIzqOTmyHa6we3vnE0um?p=preview

**Comment by jkphl** [comment]
@mpiasta-ca I looked into this issue now (sorry for not responding earlier!) and I can't find anything that's wrong on *svg-sprite*'s side. I also read https://github.com/angular/material/issues/7381 and it looks like you found the reason of your problems there. I'll close this issue for now — please feel free to get back here in case you still encounter problems.

**Comment by urbantrout** [comment]
I just had the same problem. When I removed all clipPaths and filled the paths instead it finally worked.
