### ISSUE TITLE
Latest Node version on windows causes [Build Error] Skipping "%s" (%s) error

### ISSUE THREAD

**Issue by thanuzz** [jkphl/gulp-svg-sprite#48]
Hi!

Until this morning I had a perfectly fine working gulp-svg-sprite (v 1.2.19) task running with the following config: 

```
{
    mode: {
        defs: {
            dest: '',
            sprite: 'service-icons.svg'
        }
    },
    svg: {
        xmlDeclaration: false,
        doctypeDeclaration: false
    }
}
```

And the following Gulp task:

```
gulp.task('service-icons', function () {  
    return gulp.src(config.src + 'images/service-icons/*')  
      .pipe(svgmin())  
      .pipe(svgsprite(config.svgConfig))  
      .pipe(gulp.dest(config.build + config.img.svg.path));  
});
```

This morning I've updated node.js to the latest version on Windows (via node-v4.3.1-x86.msi).
Since then I've got the following build error on the gulp-svg-sprite task.

> Skipping "%s" (%s) error

Can't get it to work anymore, what I've tried/concluded this far:
- my svg source files do not contain '%s'
- disabling SVGO via transform: [] does not solve it
- Adding { prefix: '' } to config > mode.defs does not solve it
- disabling svgmin() does not solve it.
- restarting pc after node install and updated dependencies

Any help, tips or tricks would be much appreciated, thanks in advance!

**Comment by jkphl** [comment]
@thanuzz Thanks for reporting. I don't have a Node instance on Windows handy right now, and I won't be able to spend time on this for at least a couple of days, but I'd first recommend re-installing (not only updating) all the dependencies by removing the `node_modules` directory and running `npm install`. Re-installing has already helped some other people with similar problems.

**Comment by thanuzz** [comment]
Thanks Joschi! Your answer solved the issue.

**Comment by jkphl** [comment]
@thanuzz Glad it worked out! :+1:

**Comment by DocOlson** [comment]
I am having the same issue on linux (debian jessie). 
nodejs version 4.4.4
gulp-svg-sprite 1.3.1
gulp 3.9.0

`gulp.task('svgsprite', function () {
    var config = {
        mode: {
            symbol: {
                dest: '.',
                sprite: './sprite.svg',
                bust: false,
                example: true,
            }
        }
    };

    return gulp.src(svg_src)
        .pipe(plumber())
        .pipe(svg(config)).on('error', function (error) {
            console.log(error);
        })
        .pipe(gulp.dest(svg_dst));
});`

When I make any changes to the svg source folder, this is the result:

> { [Error: Skipping "%s" (%s)]
  message: 'Skipping "%s" (%s)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-svg-sprite',
  __safety: { toString: [Function: bound ] } }

**Comment by DocOlson** [comment]
Insane stupidity on my end: one of the source svgs was malformed.
But: the error message could have been more clear about the error's nature.

**Comment by jkphl** [comment]
@DocOlson Thanks for reporting. As you might imagine the error message is meant as a template string. The thrown by *xmldom* should substitute the `%s` — no idea why that doesn't work with the Gulp wrapper. :/

**Comment by mimoYmima** [comment]
same issue here too, used npm to replace gulp and gulp-svg-sprite but still getting the error with %s in it which isn't helpful unfortunately.  I quickly looked at my svg files and they look ok, @docolson what malformation threw the task off for you?  I'm just saving files out of illustrator not writing them myself and it's been working great til this morning, something went bad...

**Comment by mimoYmima** [comment]
just fixed this as well by removing all my svgs and running gulp then adding them back in one by one to figure out which was malformed... there must be a better way...?

**Comment by jkphl** [comment]
@mimoYmima As I stated earlier this seems to be a problem between *xmldom* and *gulp*. Nevertheless, I'll reopen this issue and see if there's something I can do about it. I don't think I'll find the time to work on this anytime soon, though, so please bear with me. 

Btw it would be nice if you could upload the malformed SVG so I could use that for reproducing the error. Thanks!

**Comment by codev0** [comment]
Hi there.
I have same issue.

My task:
```javascript
const paths = {
    svg: {
        src: `${dirs.src}/svg/`,
        out: `${dirs.out}/assets/svg/`,
    }
};
gulp.task('svg', () => {
    return gulp.src(paths.svg.src)
        .pipe(plumber())
        .pipe(svgSprite({
            mode: {
                "symbol": {
                    "dest": "./build/assets/svg/",
                    "inline": true
                }
            },
            svg: {
                xmlDeclaration: false,
                doctypeDeclaration: false
            }
        }).on('error', (error) => {
            console.log(error)
        }))
        .pipe(gulp.dest(paths.svg.out))
});
```
I try to use with Sketch generated icons, and with entypo icons.
Links to SVGs:
From Sketch https://www.dropbox.com/s/jri15xxq48dvdrb/icon.svg?dl=0
From entypo https://www.dropbox.com/s/33yzfme0i2yvqm9/users.svg?dl=0

**Comment by roobottom** [comment]
I'm also having this same issue on Mac. I'm also using Sketch to create my original svgs

I tried cleaning up my SVG files via [SVGOMG](https://jakearchibald.github.io/svgomg/), but that didn't help either.

[Icon source files are here.](https://github.com/roobottom/roobottom-2017/tree/master/_source/icons)

**Comment by roobottom** [comment]
I'm an idiot! Solved by changing:

```
gulp.src('./_source/icons')
```

to

```
gulp.src('./_source/icons/**/*')
```

**Comment by bayzeel** [comment]
I had the same problem and tried all solutions above, but it still was an error, problem was in one of the svg files generated by Avocode, in the title of the svg file was non-breakable space "&nbsp;" after removing which, gulp started working correctly.

**Comment by HelgVolkov** [comment]
Hi there! When you save svg-files, you must check 2 things:
1. Preserve illustrator editing capabilities. Set "No"
2. Use artboards. Set "Yes"

It was helpful for me.

**Comment by jkphl** [comment]
Closing this again due to inactivity
