### ISSUE TITLE
SVG ID# Names

### ISSUE THREAD

**Issue by jackfearing** [jkphl/gulp-svg-sprite#50]
Is there a specific setting I need to use to allow ID names to display in my SVG files when processing them through gulp-svn-sprite? The reason I ask is because when I export my SVG out of illustrator I can see the ID names in the exported code. I guess the goal is to get the ID names to display on the paths. See below example from Illustrator:

`<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 16"><title>eyepreso</title><g id="eye"><path id="outer" d="M12,4C4.1,4,0,12,0,12s3.1,8,12,8c8.1,0,12-8,12-8S20.1,4,12,4Zm0,13a4.89,4.89,0,0,1-5-5,4.89,4.89,0,0,1,5-5,4.89,4.89,0,0,1,5,5A4.89,4.89,0,0,1,12,17Z" transform="translate(0 -4)"/></g><g id="inner"><path id="inner-2" data-name="inner" d="M12,9a3,3,0,1,0,3,3A3,3,0,0,0,12,9Z" transform="translate(0 -4)"/></g></svg>`

**However when I run my gulp task I'm not seeing the ID name on the paths: Here is what is displayed:**

`<symbol viewBox="0 0 24.02 16" id="eyepreso"><title>eyepreso2</title><path data-name="outer" d="M12.01 0c-7.94 0-12 8-12 8s3.07 8 12 8c8.09 0 12-8 12-8s-3.94-8-12-8zm0 13a4.88 4.88 0 0 1-5-5 4.88 4.88 0 0 1 5-5 4.88 4.88 0 0 1 5 5 4.88 4.88 0 0 1-5 5z"></path><path data-name="inner" d="M12.01 5a3 3 0 1 0 3 3 3 3 0 0 0-3-3z"></path></symbol>`

**Below is my gulp task:**
`// Basic configuration example for SVG Sprite
var config                  = {
    shape               : {
        dimension       : {               // Set maximum dimensions
            maxWidth    : 32, 			 // Max. shape width
            maxHeight   : 32, 			// Max. shape width
            precision   : 2,           // Floating point precision
            attributes  : true,      // Width and height attributes on embedded shapes

        },
        spacing         : {            // Spacing related options
            padding     : 0,		  // Padding around all shapes
            box         : 'content'  // Padding strategy (similar to CSS `box-sizing`)
        },
        dest            : 'intermediate-svg'    // Keep the intermediate files
    },
    svg                     : {                           // General options for created SVG files
        xmlDeclaration      : false,                     // Add XML declaration to SVG sprite
        doctypeDeclaration  : false,                    // Add DOCTYPE declaration to SVG sprite
        namespaceIDs        : true,                    // Add namespace token to all IDs in SVG shapes
        dimensionAttributes : true,                   // Width and height attributes on the sprite
        rootAttributes: {
            width: 0,
            height: 0,
            style: 'position:absolute; background:none !important'
        },
    },
    mode                : {
        view            : {         // Activate the «view» mode
            bust        : false,
            render      : {
                scss    : true      // Activate Sass output (with default options)
            }
        },
        css             : {
            example     : true
        },
        inline          : true,
        symbol          : true     // Activate the «symbol» mode
    }
};

// Build SVG sprites and move to build folder
gulp.task('svgSprite', function() {
	return gulp.src('assets/svg/*.svg')
		.pipe(svgSprite(config))
		.pipe(gulp.dest('assets/build/svg'))
		.pipe(notify({ message: 'SVG task complete'}));
});

// Images: Removes images not in src folder
gulp.task('cleanSVG', function(){
  del(['assets/build/svg/**/*', '!assets/svg', '!assets/svg/**/*'])
});`

**Comment by CNek** [comment]
Same issue here, even when passing these additional parameters :
`	shape               : {
		transform       : [
			{ svgo       : {
					plugins : [
						{ cleanupIDs: false },
						{ mergePaths: false },
						{ removeUselessStrokeAndFill: false },
						{ cleanupAttrs: false }
					]
				}
			}
		] 
	}	`

**Comment by CNek** [comment]
You can fiddle with svgo plugin option,
here is my working config :

```
// gulp-svg-sprite config
var config = {
	mode: {
		symbol: { // symbol mode to build the SVG
			dest: "sprite", // destination foldeer
			sprite: "sprite.svg", //sprite name
			example: true // Build sample page
		}
	},
	transform: [
                {svgo: {
                    plugins: [
                        { removeViewBox: false },
                        { removeUselessStrokeAndFill: false },
                        { cleanupIDs: false },
                        { mergePaths: false },
                        { removeUnknownsAndDefaults: false }
                    ]
                }}
            ],
	svg: {
		xmlDeclaration: false, // strip out the XML attribute
		doctypeDeclaration: false, // don't include the !DOCTYPE declaration
		namespaceIDs: false
	}
};
```

Credit to https://github.com/jkphl/grunt-svg-sprite/issues/28

**Comment by jackfearing** [comment]
That worked for me -- thanks!
