### ISSUE TITLE
SVG dimensionAttributes boolean not being respected

### ISSUE THREAD

**Issue by mcraiganthony** [jkphl/gulp-svg-sprite#51]
When SVG dimensionAttributes boolean is set to **false** the generated sprite still has height and width attributes on the symbols.

xmlDeclaration and doctypeDeclaration work as expected.

I reverted to 1.2.19 to verify.

**Comment by jkphl** [comment]
Thanks for reporting, @mcraiganthony! I'll check that asap!

**Comment by jkphl** [comment]
@mcraiganthony I tested with both *svg-sprite* and *gulp-svg-sprite* and both behave correctly / as expected. Could you please double-check / confirm that you're using a configuration like this:

```js
var config = {
    svg: {
        dimensionAttributes: false
    }
}
```

I'm asking because the option used to be somewhere at `shapes.dimensions` (or similar) a couple of releases ago. Thanks for confirming!

**Comment by mcraiganthony** [comment]
@jkphl Yep. See my config beflow. I'll have a co-worker update to 1.3 and see what happens.

<img width="337" alt="screen shot 2016-05-16 at 4 08 10 pm" src="https://cloud.githubusercontent.com/assets/1093578/15302333/6b932a4e-1b80-11e6-8c4e-b181d2e0ea2c.png">

**Comment by mcraiganthony** [comment]
@jkphl My co-worker updated to 1.3 and sees the same results ... sprite symbols have width and height attributes.

**Comment by jkphl** [comment]
That's super strange. I didn't test with symbol mode, it was view mode IIRC, so I'll do that tomorrow and let you know. Thanks for helping!

**Comment by hesselberg** [comment]
+1 on this -- will have to downgrade until fixed :-)

**Comment by jkphl** [comment]
No idea what the exact reason was (I suspect a change inside *lodash* with the handling of `NodeList`s), but it should be fixed now (new release 1.3.1). Can you confirm?

**Comment by hesselberg** [comment]
Yes, works perfectly :-) thanks! 👍

**Comment by mcraiganthony** [comment]
Thanks @jkphl! Much appreciated.

**Comment by jkphl** [comment]
@mcraiganthony @hesselberg Glad that it worked for you! :)
