### ISSUE TITLE
Decapitated Bird

### ISSUE THREAD

**Issue by mcraiganthony** [jkphl/gulp-svg-sprite#52]
I have an SVG that is being mangled. The bird's head is effectively removed from its body and moved to new coordinates. In the CodePen example below you'll see the original SVG code followed by the output SVG code.

See: http://codepen.io/mcraiganthony/pen/KzEBaq

<img width="947" alt="screen shot 2016-05-16 at 4 40 47 pm" src="https://cloud.githubusercontent.com/assets/1093578/15303295/027bf7a2-1b85-11e6-8b51-ff828cf0ad24.png">

I've had great success using gulp-svg-sprite with other, similar animations. It's saved me a TON of time. Here is an example: http://codepen.io/mcraiganthony/pen/XdPvmg

Any help would be appreciated. If you feel like this is the wrong forum for such a question, feel free to delete it. Thanks!

**Comment by jkphl** [comment]
@mcraiganthony Have you already tried playing with the SVGO plugins and selectively enabling / disabling them? This looks very much like an SVGO plugin being too agressive ... You could use the [online configurator](https://jkphl.github.io/svg-sprite) ("SVG shape transformations") to quickly locate the malicious plugin ... Please let me know if that helps!

**Comment by mcraiganthony** [comment]
@jkphl I was leaning toward that same conclusion. Thanks for the link!

**Comment by jkphl** [comment]
@mcraiganthony Any success with this one yet?

**Comment by mcraiganthony** [comment]
@jkphl Still working on it. But skipping SVGO absolutely fixes it. Now I'm going to try various SVGO configs to see if I can pinpoint the problem.

Last week I tried https://jakearchibald.github.io/svgomg/ and disabled all options but still resulted in decapitated bird.

**Comment by mcraiganthony** [comment]
@jkphl AH! I had no idea SVGOMG features list was scrollable! The **round/rewrite transforms** feature was the culprit.

**Comment by jkphl** [comment]
@mcraiganthony Awesome! So you got it to work now also with *(gulp-)svg-sprite*?

**Comment by mcraiganthony** [comment]
Yes sir!
