### ISSUE TITLE
Combine symbols and views

### ISSUE THREAD

**Issue by seamofreality** [jkphl/gulp-svg-sprite#55]
Is there a way to combine both symbols and views in one file?

**Comment by jkphl** [comment]
Hi @seamofreality, it is surely possible to have a combined sprite, but *(gulp-)svg-sprite)* doesn't support this out of the box at the moment. There [has even been an issue](https://github.com/jkphl/svg-sprite/pull/81) discussing the topic, but so far I didn't find the time to work on this. I can imagine that this would be possible by writing a custom rendering template, but a built-in solution would definitely be preferable. I suggest you to file an issue in the [svg-sprite repo](https://github.com/jkphl/svg-sprite/issues) and keep an eye on it. I'll close this one here, as it should become an *svg-sprite* core feature and not only affect the Gulp wrapper. Thanks again!
