### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by custa1200** [jkphl/gulp-svg-sprite#57]
Is it possible for svg-sprite to output items as a mustache/ejs/jade/etc... partial to include in different frameworks making it easier be consumed by things like Express/Koa?

**Comment by jkphl** [comment]
Hi @custa1200, I bet it's possible by writing / using custom rendering templates. Personally, I don't have any clue of all the technologies you mentioned except Mustache, but as *svg-sprite* uses Mustache templates itself, you will be able to generate arbitrary (text based) output. You will want to read [this](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#rendering-configurations) and [this](https://github.com/jkphl/svg-sprite/blob/master/docs/templating.md) to get started with writing your own templates. Good luck!
