### ISSUE TITLE
Removing <style> elements from compiled sprite.svg

### ISSUE THREAD

**Issue by adamgilmour** [jkphl/gulp-svg-sprite#66]
Hi, just wondering if there's an option to remove the <style> elements from the sprite.svg that's compiled?

Ideally I'd like to grab all src .svg files, compile them into a sprite (which it current does great!) which then strips the styling to enable fill overwriting with css, when the sprite is used. Reason being, I'd also like to keep a base copy to include the original svg if needed with its original colours

<symbol id="logo" viewBox="0 0 1802.3 187">
THIS ----> <style>.fst0{fill:#29abe2}.fst1{fill:#37474f}.fst2{fill:#30c4ff}</style> <---- THIS
<path/>.........
I've read through the documentation but can't find what I'm looking for. Apologies if I've missed it.

Thanks

**Comment by jkphl** [comment]
@adamgilmour Thanks for asking. The short answer: No, there is no such option, at least not directly.

The long version: *svg-sprite* tries to stick to its most basic purpose which is to create sprites. There are plenty of libraries out there which are really good at parsing and manipulating SVG / XML, so *svg-sprite* doesn't try to replace them. Instead, you should pipe *svg-sprite*'s output to a second, specialized process which strips out the `<style>` elements.

That being said, *svg-sprite* might offer you a cheap possibility to do so: You should be able to use a [global post-processing transformation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) and apply a regex based replacement like this (off the top of my head, untested):

```js
var config = {
    svg: {
        transform: [
            /**
             * Strip out all <style> elements
             *
             * @param {String} svg                  Sprite SVG
             * @return {String}                     Processed SVG
             */
            function(svg) {
                return svg.replace(~<style>.*?</style>~i, '');
            }
        ]
    }
}
```

Please let me know if this works for you.

**Comment by adamgilmour** [comment]
@jkphl Thanks for your reply :)

Many thanks for the function, unfortunately there was a syntax error in the regex code you supplied. I don't have any experience in regular expression but did a search and ended up using the following code which worked to remove all `<style>` elements from the compiled sprite:

`return svg.replace(/(<style.*?<\/style>)/g, "")`

Works great :)

**Comment by jkphl** [comment]
@adamgilmour Perfect, thanks for your feedback (and sorry for the typo — as I said, the regex was off the top of my head and untested). Happy spriting!

**Comment by adamgilmour** [comment]
Just to add to this.. I had to remove the svg fill:#xxxxxx styling which was also stopping me from overwriting with css. The final function looks like:

```
function(svg) {
    return svg.replace(/(<style.*?<\/style>)/g, "").replace(/(fill=\"#([0-9a-f]{6})\")/g, "");
}
```

**Comment by ajilderda** [comment]
That's great @adamgilmour . I've changed the lines to the following so that it also replaces caps (`#FF0000`) and shorthand hex colors (`#ff0`):
```
function(svg) {
    return svg.replace(/(<style.*?<\/style>)/g, "").replace(/(fill=\"#([0-9a-fA-F]{6})\")/g, "").replace(/(fill=\"#([0-9a-fA-F]{3})\")/g, "");
}
```

**Comment by petrchutny** [comment]
I love you all in this thread @jkphl, @adamgilmour & @ajilderda :) Just used the last regex to my total happiness!
