### ISSUE TITLE
What are the system requirements for this plugin?

### ISSUE THREAD

**Issue by kasienna** [jkphl/gulp-svg-sprite#69]
I'm working with gulp-svg-sprites and as far as it was on my machine it was fine, but then remote gitlab build does not generate svg sprite file at all. Could it be caused by lack of some programs installed on the machine, f.e. imagemagick?

**Comment by jkphl** [comment]
@kasienna I'm sorry but I don't think I can add anything of value to this question. Node respectively `npm` should take care of any dependencies needed by *svg-sprite* / *gulp-svg-sprite*. Did you try to increase the log level to `"debug"`? What's the output?

Maybe an idea (at least this is true for our servers): In case you are using a hardened Linux kernel, you might have to adjust the file permissions and / or PaX features of some binaries (especially the PhantomJS binary).

Sorry I cannot help you further. Please let me know if you succeed. Thanks.

**Comment by kasienna** [comment]
Thanks, I was suspecting that it might be something with PhantomJS

**Comment by jkphl** [comment]
In my experience, if it's really an issue with PhantomJS you should be able to so see something in the server logs (e.g. security related logs).
