### ISSUE TITLE
clip path (and others) being lost

### ISSUE THREAD

**Issue by vincelee888** [jkphl/gulp-svg-sprite#71]
when running a new svg through, it is not displaying correctly.

here is the output: https://dev-web-streetsupport.azurewebsites.net/find-help/accommodation/ on the first icon (read our advice guide), you can see the clip path around the speech bubble has been lost, and the line and window has not been clipped. also, there should be a white frame around the window.

viewing it via gulp-svg-sprite's generated preview page, it appears to be ok:

![with-embedded](https://user-images.githubusercontent.com/73041/28162696-ebec3ee2-67bf-11e7-9aba-139ce853a16d.PNG)

however, when i delete the embedded svg markup from the source via dev tools, it displays incorrectly:

![without-embedded](https://user-images.githubusercontent.com/73041/28162695-ebea86ce-67bf-11e7-82e9-cbf3a3483954.PNG)

any ideas, or should i try and build the image in a different way?

**Comment by vincelee888** [comment]
something to do with the clip path - i re-drew using intersections

**Comment by jkphl** [comment]
It sounds like this might be related to https://github.com/jkphl/svg-sprite/issues/233. So, you could solve your issue by altering the source SVG?

**Comment by vincelee888** [comment]
no worries, i re-drew it and fixed it. cheers!
