### ISSUE TITLE
Problem with the common property inside the configuration

### ISSUE THREAD

**Issue by andreecordova** [jkphl/gulp-svg-sprite#73]
Hello, I was triying to create a configuration that have a custom common placeholder for my generated scss file, but when I saw my generated files. I notice that the placeholder is not extended in any icon class I had. My configuration is this:
```
config = {
    mode: {
      css: {
        dest: "css",
        common: "svg-general",
        bust: false,
        sprite: "sprites/general.svg",
        render: {
          scss: {
            dest: "./sprites/_sprite.scss"
          }
        }
      }
    }
  }
```
If I don't use the common property, It would generate for default %svg-common and in that case I saw that that placeholder is extended in any icon class. Why happened that or How can I fixed that?

**Comment by jkphl** [comment]
@andreecordova I'm afraid but I think I don't really understand your problem / question. Could you please add some CSS / SCSS code samples with the expected and the real results? Thanks!

**Comment by andreecordova** [comment]
Hi, @jkphl .
Sorry if I didn't express myself very well.

The real result of using the common property in my config:
![real_result](https://user-images.githubusercontent.com/28737769/33329504-b73509f4-d42a-11e7-98c7-656289237c93.png)

The result I want to have:
![expect_result](https://user-images.githubusercontent.com/28737769/33329490-b0e0f96e-d42a-11e7-9474-f179a686f527.png)

**Comment by jkphl** [comment]
@andreecordova First of all: sorry for the late reply.

I think what you're after is the `mode.<mode>.mixin` property, not the `mode.<mode>.common` (which is creating a common **CSS class rule**, see [documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#specific-mode-properties)).
