### ISSUE TITLE
add class="my-class" to <symbol>

### ISSUE THREAD

**Issue by 7daysofrain** [jkphl/gulp-svg-sprite#85]
Hi,

Is there a way to add a fixed class to the <symbol> tag?

Thanks

**Comment by jkphl** [comment]
@7daysofrain Sorry for not responding earlier, I'm on holiday at the moment. It's beyond *(gulp-)svg-sprite*'s scope to do SVG manipulation other than needed for sprite compilation. You can, however, use a [custom global transform to post-process](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#svg-sprite-customization) the sprite before it gets saved. You'll have to write the code for adding the CSS class yourself inside a callback function that gets executed for this purpose, see documentation. Good luck!

**Comment by 7daysofrain** [comment]
@jkphl just did that, It worked perfectly, thanks!
