### ISSUE TITLE
Optimizing "%s" with SVGO failed with error "%s"

### ISSUE THREAD

**Issue by jonnitto** [jkphl/gulp-svg-sprite#86]
Since version 1.4 I got always the following error:

`Optimizing "%s" with SVGO failed with error "%s"`

OS: macOS 10.13.6
node: v10.10.0
npm: 6.4.1

**Comment by longzheng** [comment]
I figured out the problem, it has to do with the new release of SVGO on npm which is a dependency of svg-sprite which gulp-svg-sprite is dependant on.

It seems the latest version of svgo causes svg-sprite to throw an exception with any SVG file (I think it's a compatibility issue similar to svg/svgo#1030).

I was able to "fix" this by reverting gulp-svg-sprite to 1.3.7 (and clearing my node_modules folder).

**Comment by longzheng** [comment]
Added a new issue for `svg-sprite` https://github.com/jkphl/svg-sprite/issues/276

**Comment by jkphl** [comment]
Thanks for reporting! I'll try to have a look as soon as I find some time. Closing this one in favor of https://github.com/jkphl/svg-sprite/issues/276

**Comment by web-admin** [comment]
Hi,

Any progress with it? I have the same issue and I'm using svg-sprite 1.5.0. Is the only one way at the moment to revert to ver. 1.3.7 as longzehng mentioned?

Thanks.

**Comment by chicharitomagnetico** [comment]
Having the same issue, reverting to 1.4.1 didn't work.
I'm guessing dependencies changed again.

Message:
    Optimizing "%s" with SVGO failed with error "%s"
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

**Comment by bitstarr** [comment]
Since this is being abandoned, what is the last working configuration (version numbers) of svgo, svg-sprite and gulp-svg-sprite?

**Comment by Kangouroops** [comment]
Having the same issue here.
Everything was working yesterday, and today i got this error:

> Error in plugin "gulp-svg-sprite"
> Message:
>     Optimizing "%s" with SVGO failed with error "%s"
> Details:
>     domainEmitter: [object Object]
>     domain: [object Object]
>     domainThrown: false

**Comment by Real-sense** [comment]
Менял версии, ничего не помогло, проблема в том, что пакет не умеет перезаписывать ранее сгенерированый файл(свг спрайт), его приходиться удалять и только после выполнять таск, тогда ошибки нет

**Comment by kode8** [comment]
> Менял версии, ничего не помогло, проблема в том, что пакет не умеет перезаписывать ранее сгенерированый файл(свг спрайт), его приходиться удалять и только после выполнять таск, тогда ошибки нет

Write in English ffs

**Comment by SultanMashukov** [comment]
Check your's SVG file encoding!!! Must be UTF-8

**Comment by denis991** [comment]
[11:57:31] 'svgSprive' errored after 33 ms
[11:57:31] Error in plugin "gulp-svg-sprite"
Message:
    Optimizing "%s" with SVGO failed with error "%s"
Details:
    domainEmitter: [object Object]
    domainThrown: false
    
    "gulp": "^4.0.2",
    "gulp-svg-sprite": "^2.0.1",
