### ISSUE TITLE
Problem with hover to generate stylus

### ISSUE THREAD

**Issue by tiagoporto** [jkphl/gulp-svg-sprite#9]
Hello @jkphl maybe I found another bug

I have 2 files
```
icon.svg
icon~hover.svg
```

My stylus generates

```
.svg-icon,
.svg-icon\\:regular
	background-position 0 50%
	@extend $svg-common

.svg-icon:hover,
.svg-icon\\:hover
	background-position 0 100%
	@extend $svg-common

.svg-icon-dims:hover,
.svg-icon\\:hover-dims
	width 104px
	height 104px
```

You can see these strange lines

```
.svg-icon\\:regular
.svg-icon\\:hover
.svg-icon\\:hover-dims
```

When the stylus is compiled, generates this

```
.svg-icon,
.svg-icon\:regular {
  background-position: 0 50%;
}
.svg-icon:hover,
.svg-icon\:hover {
  background-position: 0 100%;
}

.svg-icon-dims:hover,
.svg-icon\:hover-dims {
  width: 104px;
  height: 104px;
}
```

I'm on windows

**Comment by jkphl** [comment]
Hi @tiagoporto,

these lines are **fully intentional**. This way the `:hover` icon is not only accessible in a true hover state, but you can also use it intentionally in your source:

```html
<!-- Icon that will change when hovered -->
<i class="svg-icon"></i>

<!-- Icon in hover state -->
<i class="svg-icon:hover"></i>
```

It might look strange to have a colon on your CSS class name, but it's perfectly legal (just has to be escaped with a backslash in the CSS).

Regards,
Joschi

**Comment by tiagoporto** [comment]
Nice, just one thing.

In this case
```
.svg-icon-dims:hover,
.svg-icon\:hover-dims
```

Why not this?
```
.svg-icon-dims\:hover
```

**Comment by jkphl** [comment]
Because `-dims` is supposed to be a suffix to the class name. In the first line `svg-icon-dims` is the selector (and `:hover` a pseudo class), and in the second line `svg-icon\:hover-dims` is the class name. It's always `-dims` at the end (which is kinda the sense of a suffix).

**Comment by tiagoporto** [comment]
Makes sense. Thanks @jkphl

**Comment by nicksyndicate** [comment]
Thnks @jkphl
