### ISSUE TITLE
Can i minify svg before make sprite in one task?

### ISSUE THREAD

**Issue by dimkadenisov** [jkphl/gulp-svg-sprite#95]
#### I would like to minimize  icons using gulp-imagemin and make the sprite in one task. Is it possible?

It will be nice bekome something like this:

```
const gulp = require('gulp');
const svgSprite = require('gulp-svg-sprite');
const imagemin = require('gulp-imagemin');

gulp.task('svg:sprite', function() {
   gulp.src('path/to/assets/*.svg')
  .pipe(imagemin.svgo())
  .pipe(svgSprite(/* ... Insert your configuration here ... */))
  .pipe(gulp.dest('out'));
});
```

But this task of course does not work.

#### Thanks for help, dear friends.

**Comment by jkphl** [comment]
@dimkadenisov As far as I understand your example, you'd like to run SVGO on the single shapes, is that correct? Did you realize that SVGO is already part of the `svg-sprite` process? [See documentation](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#shape-transformations) for details. I don't think your suggestion is necessary.

**Comment by dimkadenisov** [comment]
@jkphl Thank you very much. And sorry for stypid question.
