### ISSUE TITLE
Optimizing "%s" with SVGO failed with error "%s"

### ISSUE THREAD

**Issue by ylokesh** [jkphl/gulp-svg-sprite#98]
Since last day, while doing the build we are getting following error:

`Optimizing "%s" with SVGO failed with error "%s"`

While problem analysis, found that one of the sub-sub-dependency i.e. SVGO has made a release last day which is causing this issue.

Can you please help us resolving this issue? or suggest an interim resolution.

Package.json
"gulp-svg-sprite": "^1.4.0"

Thanks in advance.

<img width="624" alt="Screenshot 2019-10-30 at 5 02 12 PM" src="https://user-images.githubusercontent.com/3806368/67854869-373c9100-fb37-11e9-9552-585804c6a7c5.png">

**Comment by bhupalichiplunkar** [comment]
@ylokesh did you get this resolved? If yes, could you tell me how?

**Comment by Jordan-Hall** [comment]
@bhupalichiplunkar  first try and delete the generated svg file from before.

If that doesn't work then remove node_modules and install them again

**Comment by NewDimix** [comment]
Кто то решил проблему?

**Comment by Kreeg** [comment]
@NewDimix see here #82 
Will be fixed with the new release

**Comment by Francois-Esquire** [comment]
Hi @Kreeg,  thanks for being on top of this! Do you know when we can expect the new release to be out?
